apiVersion: v1
kind: PersistentVolume
metadata:
  name: $GCE_DISK
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
#  gcePersistentDisk:
#    fsType: ext4
#    pdName: $GCE_DISK
  awsElasticBlockStore:
    volumeID: $AWS_VOLUME_ID
